
Refer to [project overview](https://docs.google.com/document/d/1QPh7cKy7fmokalWuou5Z_zqG6680rybq8CC6gmiC8RE/edit?tab=t.0) document for guidance


# Set up

Import packages
```{r}
suppressPackageStartupMessages({
  suppressWarnings({
  library(tidyverse)   # Data wrangling
  library(here)        # File management
  library(readxl)      # Read excel files
  })})
```

Set settings and universal variables
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here())
options(scipen = 999)
```


# Import data

```{r}
folder_path <- "Outputs/Annual demand met/"  
csv_files <- list.files(path = folder_path, pattern = "\\.csv$", full.names = T)

combined_df <- do.call(rbind, lapply(csv_files, read_csv))
```

# Plots

```{r}
tier_csvs = list.files("Outputs/Tier summaries/", full.names = T)


lapply(tier_csvs, function(file) {
  file_name <- basename(file) %>% tools::file_path_sans_ext()
  scenario_name = str_to_title(str_extract(file, "(?<=_)[^_]+$"))
  
  read.csv(file) %>%
  pivot_longer(-scenario_id, names_to = "du", values_to = "tier")%>%
  filter(!is.na(tier))%>%
  group_by(scenario_id)%>%
  mutate(total_n = n())%>%
  ungroup()%>%
  group_by(scenario_id, tier)%>%
  reframe(prop = n()/total_n)%>%
  unique()%>%
  ggplot(aes(scenario_id, prop, fill = as.factor(tier)))+
  geom_col(position="stack")+
  labs(x= "Scenario", y = "Proportion of Demand Units", fill = "Tier", title = scenario_name)})
```

# Handout plots
```{r}
read.csv("Outputs/Tier summaries/20260227_historical_scenarios_tiers.csv")%>%
  pivot_longer(-scenario_id, names_to = "du", values_to = "tier")%>%
  filter(!is.na(tier))%>%
  group_by(scenario_id)%>%
  mutate(total_n = n())%>%
  ungroup()%>%
  group_by(scenario_id, tier)%>%
  reframe(prop = n()/total_n)%>%
  unique()%>%
  filter(scenario_id %in% c("s0020", "s0035", "s0036", "s0037"))%>%
  ggplot(aes(scenario_id, prop*100, fill = as.factor(tier)))+
  geom_col(position="dodge")+
  labs(x= "Scenario", y = "Percentage of Demand Units", fill = "Tier")+
  theme_bw()+
  scale_x_discrete(labels = c(
    "s0020" = "Baseline",
    "s0035" = "Prioritize human health \n and safety needs", 
    "s0036" = "Prioritize 70% of \n community water demands",
    "s0037" = "Prioritize all community \n water demands"))


read.csv("Outputs/Tier summaries/20260227_historical_scenarios_tiers.csv")%>%
  pivot_longer(-scenario_id, names_to = "du", values_to = "tier")%>%
  filter(!is.na(tier))%>%
  group_by(scenario_id)%>%
  mutate(total_n = n())%>%
  ungroup()%>%
  group_by(scenario_id, tier)%>%
  reframe(prop = n()/total_n)%>%
  unique()%>%
  filter(scenario_id == "s0020")%>%
  ggplot(aes(scenario_id, prop*100, fill = as.factor(tier)))+
  geom_col(position="dodge")+
  labs(x= "Scenario", y = "Percentage of Demand Units", fill = "Tier")+
  theme_bw()+
  scale_x_discrete(labels = c("s0020" = "Baseline Scenario"))
```
```{r}
folder_path <- "Outputs/Monthly demand met/"  

scenarios <- c("s0020", "s0035", "s0036", "s0037")
dwucs_to_keep <- c("20_NU1", "NAPA", "90_PU", "MWD")

all_data <- map_dfr(scenarios, function(scenario) {
  file_path <- paste0(folder_path, scenario, "_demand_met_by_month.csv")
  df <- read.csv(file_path)%>%
      mutate(date = as.Date(date), 
             month = month(date))%>%
      filter(dwuc %in% dwucs_to_keep)%>%
      mutate(id = paste(scenario_id, dwuc, sep = ", "))%>%
      group_by(id, scenario_id, dwuc, month)%>%
      reframe(monthly_avg = median(delivery_taf),
              p25 = quantile(delivery_taf, 0.25),
              p75 = quantile(delivery_taf, 0.75))
  return(df)})

p1 = ggplot(all_data, aes(x = month, y = monthly_avg)) +
  geom_point(color = "steelblue")+
  geom_line(color = "steelblue", linewidth = 0.7) +
  geom_point(color = "steelblue", size = 0.5, alpha = 0.3) +
  facet_grid(dwuc ~ scenario_id, scales = "free_y") +
  labs(x = "Month", y = "Median Monthly Deliveries (TAF)")+ 
  theme_bw()+
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb)+
  theme(axis.text.x = element_text(angle = 55, hjust = 1),
        strip.text = element_blank(),
        panel.spacing.y = unit(1, "lines"))+
  geom_ribbon(aes(ymin = p25, ymax = p75), alpha = 0.2, fill = "blue")

ggsave("Plots/time_series_for_handout.png", p1, height = 7, width = 10)

all_data%>%
  filter(scenario_id == "s0020")%>%
  mutate(dwuc = factor(dwuc, 
                       levels = c("20_NU1", "90_PU", "MWD", "NAPA"),
                       labels = c("20_NU1 (Davis, Woodland)", "90_PU (Huron, Avenal, Coalinga)", "MWD (Metropolitan)", "NAPA (Napa, St. Helena, Calistoga)"))) %>%
  ggplot(aes(x = month, y = monthly_avg)) +
  geom_point(color = "steelblue")+
  geom_line(color = "steelblue", linewidth = 0.7) +
  geom_point(color = "steelblue", size = 0.5, alpha = 0.3) +
  facet_wrap(~dwuc, scales = "free_y", ncol = 2) +
  labs(x = "Month", y = "Median Monthly Deliveries (TAF)")+ 
  theme_bw()+
  scale_x_continuous(breaks = seq_along(month.abb), labels = month.abb)+
  theme(axis.text.x = element_text(angle = 55, hjust = 1))+
  geom_ribbon(aes(ymin = p25, ymax = p75), alpha = 0.2, fill = "blue")
```




# Archive
```{r}
combined_df%>%
  ggplot(aes(percent_demand_met, fill = scenario_id))+
  geom_density(alpha = 0.1, position = "identity") +
  labs(x = "% Annual Demand Met", y = "Density", subtitle = "Across all demand units and all years")

combined_df%>%
  filter(scenario_id == "s0045")%>%
  ggplot(aes(percent_demand_met))+
  geom_histogram(aes(y = ..count../sum(..count..)*100), fill = "coral1", colour = "black")+
  labs(x = "% Annual Demand Met", y = "% of Values (across all demand units and years)", subtitle = "Scenario S0045, across all demand units and years")


library(ggridges)

ggplot(combined_df, aes(x = percent_demand_met, y = scenario_id, fill = scenario_id)) +
  geom_density_ridges(
    aes(height = after_stat(density)),
    stat = "density",
    scale = 0.9,
    alpha = 0.7) +
  scale_x_continuous(expand = expansion(mult = c(0.01, 0.01))) +
  theme_ridges() +
  labs(x = "% demand met", y = "Scenario", subtitle = "All years & demand units")+
  theme(legend.position = "none")
```

```{r}
grouped = combined_df %>%
  group_by(scenario_id, dwuc) %>%
  summarise(
    n_years = n(),
    pct_met_100 = mean(percent_demand_met >= 100, na.rm = TRUE) * 100,
    pct_met_90 = mean(percent_demand_met >= 90, na.rm = TRUE) * 100,
    pct_met_75 = mean(percent_demand_met >= 75, na.rm = TRUE) * 100,
    pct_met_50 = mean(percent_demand_met >= 50, na.rm = TRUE) * 100,
    median_demand_met = median(percent_demand_met, na.rm = T),
    min_demand_met = min(percent_demand_met, na.rm = TRUE),
    .groups = 'drop')

ggplot(grouped, aes(x = pct_met_100)) +
  geom_histogram(binwidth = 5, fill = "steelblue", alpha = 0.7)+ 
  geom_vline(xintercept = c(50, 70, 90), linetype = "dashed", size = 1) +
  facet_wrap(~scenario_id, ncol = 4) +
  labs(title = "Distribution of % Years with Full Demand Met, by Demand Unit",
       x = "% Years with 100%+ Demand Met",
       y = "# of Demand Units") +
  theme_bw()


ggplot(grouped, aes(x = min_demand_met)) +
  geom_histogram(binwidth = 5, fill = "coral4", alpha = 0.7)+ 
  geom_vline(xintercept = c(50, 70, 90), linetype = "dashed", size = 1) +
  facet_wrap(~scenario_id, ncol = 4) +
  labs(title = "Distribution of Minimum Demand Met by Demand Unit",
       x = "% Demand Met in Worst Year",
       y = "# of Demand Units") +
  theme_bw()

ggplot(grouped, aes(x = median_demand_met)) +
  geom_histogram(binwidth = 5, fill = "pink4", alpha = 0.7)+ 
  geom_vline(xintercept = c(50, 70, 90), linetype = "dashed", size = 1) +
  facet_wrap(~scenario_id, ncol = 4) +
  labs(title = "Distribution of Median % Demand Met by Demand Unit",
       x = "Median % Demand Met",
       y = "# of Demand Units") +
  theme_bw()

grouped
```




